/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryapp;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author akhmad rafli
 */
public class Transaction extends javax.swing.JFrame {

   
    private String full_name;

    /**
     * Creates new form Transaction
     */
    //inheritance
    public Transaction() {
        initComponents();
        LogicTr logic = new LogicTr();
        //ModelTrans model = new ModelTrans();
        tf_total.setText(logic.subtotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_total = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_return = new javax.swing.JTextField();
        btn_Count = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cb_service = new javax.swing.JComboBox<>();
        btn_clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tf_weight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_cash1 = new javax.swing.JTextField();
        btn_Pay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 30)); // NOI18N
        jLabel1.setText("TRANSACTION");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("Full Name:");

        tf_name.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        tf_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nameKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Weight/Kg:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("Sub Total Rp.");

        tf_total.setEditable(false);
        tf_total.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel13.setText("Cash Rp.");

        tf_return.setEditable(false);
        tf_return.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tf_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_returnActionPerformed(evt);
            }
        });
        tf_return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_returnKeyPressed(evt);
            }
        });

        btn_Count.setBackground(new java.awt.Color(203, 203, 203));
        btn_Count.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btn_Count.setText("Count");
        btn_Count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CountActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(203, 203, 203));
        btn_exit.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("Service:");

        cb_service.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cb_service.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose:", "Reguler", "Dry Cleaning", "Wet Cleaning", "Express Cleaning", " " }));

        btn_clear.setBackground(new java.awt.Color(203, 203, 203));
        btn_clear.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryapp/Image/Logo Laundry'.png"))); // NOI18N

        tf_weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_weightActionPerformed(evt);
            }
        });
        tf_weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_weightKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Return Rp");

        tf_cash1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tf_cash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cash1ActionPerformed(evt);
            }
        });
        tf_cash1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_cash1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_cash1KeyTyped(evt);
            }
        });

        btn_Pay.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btn_Pay.setText("Pay");
        btn_Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Pay, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_total)
                                    .addComponent(tf_cash1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_service, 0, 245, Short.MAX_VALUE)
                            .addComponent(tf_weight)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(96, 96, 96)
                        .addComponent(tf_return)))
                .addGap(117, 117, 117)
                .addComponent(jLabel2)
                .addGap(395, 395, 395))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_service, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_total, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_cash1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_return, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Count, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_returnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_returnActionPerformed

    private void tf_returnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_returnKeyPressed
       
    }//GEN-LAST:event_tf_returnKeyPressed

    private void btn_CountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CountActionPerformed
   boolean choose = true;
   if (tf_name.getText().isEmpty()){
       JOptionPane.showMessageDialog(null, "Please input your name",
               "Warning", JOptionPane.ERROR_MESSAGE);
 
   }
   if (cb_service.getSelectedIndex()==0){
       JOptionPane.showMessageDialog(null, "Please input Service",
               "Warning", JOptionPane.ERROR_MESSAGE);
       choose = false;
   }
   if (choose == true){
       
   String service = cb_service.getSelectedItem().toString();
   
     //enkap
   ModelTr modeltr = new ModelTr();
   modeltr.setService(service);
   
   //abstraksi
   LogicTr logictr = new Logic2();

   //polymorphism
   int service1 = logictr.returnService(modeltr);

   int weight = Integer.parseInt(tf_weight.getText());
       
   int subtotal = service1*weight;
   tf_total.setText(String.valueOf(subtotal));
    
        }   
    }//GEN-LAST:event_btn_CountActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        int dialog = JOptionPane.showOptionDialog(this, "Are you sure?", "Exit",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (dialog == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Thank you for using this program");
            System.exit(0);
        }        
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        
        tf_name.setText("");
        cb_service.setSelectedIndex(0);
        tf_weight.setText("");
        tf_total.setText("");
        tf_return.setText("");
        tf_cash1.setText("");
      
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tf_nameActionPerformed

    private void tf_weightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_weightKeyTyped
        // TODO add your handling code here:
        char cDigit = evt.getKeyChar();
if(!Character.isDigit(cDigit)){
evt.consume();
}
    }//GEN-LAST:event_tf_weightKeyTyped

    private void tf_cash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cash1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cash1ActionPerformed

    private void tf_cash1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cash1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cash1KeyPressed

    private void tf_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nameKeyTyped
        // TODO add your handling code here:
         
    }//GEN-LAST:event_tf_nameKeyTyped

    private void btn_PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PayActionPerformed
        // TODO add your handling code here:
    String service = cb_service.getSelectedItem().toString();
   
     //enkap
   ModelTr modeltr = new ModelTr();
   modeltr.setService(service);
   
   //abstraksi
   LogicTr logictr = new Logic2();
   
   
   int service1 = logictr.returnService(modeltr);
   
   int weight= Integer.parseInt(tf_weight.getText());
       
   int subtotal = service1*weight;
   tf_total.setText(String.valueOf(subtotal));
   
   int cash = Integer.parseInt(tf_cash1.getText());
   int return_cash = cash-subtotal;
   tf_return.setText(String.valueOf(return_cash));
    
               
    }//GEN-LAST:event_btn_PayActionPerformed

    private void tf_weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_weightActionPerformed

    private void tf_cash1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cash1KeyTyped
        // TODO add your handling code here:
                char cDigit = evt.getKeyChar();
if(!Character.isDigit(cDigit)){
evt.consume();
}
    }//GEN-LAST:event_tf_cash1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Count;
    private javax.swing.JButton btn_Pay;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_exit;
    private javax.swing.JComboBox<String> cb_service;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_cash1;
    public static javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_return;
    private javax.swing.JTextField tf_total;
    private javax.swing.JTextField tf_weight;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
